### ISSUE TITLE
pipeline_mvadapter_i2mv_sdxl.py", line 548 ... Cannot generate a cpu tensor from a generator of type cuda

### ISSUE THREAD

**Issue by marcovth** [huanngzh/MV-Adapter#12]
```
2024-12-09T21:16:44.825813 - 
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 7/7 [00:03<00:00,  1.86it/s]2024-12-09T21:16:44.825813 - 
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 7/7 [00:03<00:00,  1.90it/s]2024-12-09T21:16:44.825813 - 
2024-12-09T21:18:32.463680 - !!! Exception during processing !!! Cannot generate a cpu tensor from a generator of type cuda.
2024-12-09T21:18:32.464680 - Traceback (most recent call last):
  File "A:\ComfyuiDesktop\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\ComfyuiDesktop\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\ComfyuiDesktop\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "A:\ComfyuiDesktop\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\ComfyuiDesktop\ComfyUI\custom_nodes\ComfyUI-MVAdapter\nodes.py", line 459, in sample
    images = pipeline(
             ^^^^^^^^^
  File "A:\ComfyuiDesktop\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "A:\ComfyuiDesktop\ComfyUI\custom_nodes\ComfyUI-MVAdapter\mvadapter\pipelines\pipeline_mvadapter_i2mv_sdxl.py", line 548, in __call__
    latents = self.prepare_latents(
              ^^^^^^^^^^^^^^^^^^^^^
  File "A:\ComfyuiDesktop\python_embeded\Lib\site-packages\diffusers\pipelines\stable_diffusion_xl\pipeline_stable_diffusion_xl.py", line 721, in prepare_latents
    latents = randn_tensor(shape, generator=generator, device=device, dtype=dtype)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\ComfyuiDesktop\python_embeded\Lib\site-packages\diffusers\utils\torch_utils.py", line 67, in randn_tensor
    raise ValueError(f"Cannot generate a {device} tensor from a generator of type {gen_device_type}.")
ValueError: Cannot generate a cpu tensor from a generator of type cuda.
```

**Comment by marcovth** [comment]
![image](https://github.com/user-attachments/assets/3ba84324-0da3-4fb9-aa7f-38f8bc0f8942)
